# Generated by Django 3.1.4 on 2021-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210110_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
