# Generated by Django 3.1.4 on 2021-01-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210110_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscription_start',
            new_name='subscription_to',
        ),
    ]
