# Generated by Django 3.1.4 on 2021-01-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
