import django.db.models.deletion
from django.db import migrations, models
`  # Generated by Django 3.1.4 on 2021-02-08 20:54


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_usersubscription_user'),
        ('users', '0011_auto_20210207_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_to',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usersubscription'),
        ),
    ]
