# Generated by Django 3.1.4 on 2021-01-16 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('page_type', models.CharField(choices=[('INDUSTRY', 'industry'), ('SERVICES', 'services'), ('ENGINEERING', 'engineering')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='pages.headersection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'page_type', 'updated_at'),
            },
        ),
    ]
