# Generated by Django 3.1.4 on 2021-01-16 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='header',
        ),
        migrations.AddField(
            model_name='page',
            name='header_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='header_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HeaderSection',
        ),
    ]
