# Generated by Django 3.1.4 on 2021-01-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210116_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('INDUSTRY', 'industry'), ('SERVICES', 'services'), ('ENGINEERING', 'engineering')], default='', max_length=20),
        ),
    ]
