# Generated by Django 3.1.4 on 2021-01-16 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_auto_20210116_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='about_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
