# Generated by Django 3.1.4 on 2021-01-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210116_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='about_title',
        ),
        migrations.AddField(
            model_name='page',
            name='services_1_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='services_1_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='services_1_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='services_2_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='services_2_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='services_2_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='services_3_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='services_3_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='services_3_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='services_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='services_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
