# Generated by Django 3.1.4 on 2021-01-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210116_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
