# Generated by Django 3.1.4 on 2021-01-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='view_count',
        ),
        migrations.CreateModel(
            name='PageAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='pages.page')),
            ],
        ),
    ]
