# Generated by Django 3.1.4 on 2021-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210116_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanalytics',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageanalytics',
            name='country',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageanalytics',
            name='lat',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageanalytics',
            name='lng',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
