# Generated by Django 3.1.4 on 2021-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_mainpageanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='about_subtitle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='about_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
