# Generated by Django 3.1.4 on 2021-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210116_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='about_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
