# Generated by Django 3.1.4 on 2021-01-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210116_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='contact_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
