# Generated by Django 3.1.4 on 2021-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_page_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='contact_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
