# Generated by Django 3.1.4 on 2021-01-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210116_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='main_color',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='services_enable',
            field=models.BooleanField(default=False),
        ),
    ]
